// Where the busiest airports are (TR-49): booking import fills a leg's empty `city` or `country`
// from its IATA code, since a boarding pass often prints only "LIS" or "Lisbon LIS". A small
// static table, not a lookup service: an airport that isn't here just keeps what the model read.
// Countries are English short names, the same wording the model and the golden set use.

const US = 'United States';

/** IATA code → [city, country]. */
export const AIRPORTS: Record<string, readonly [string, string]> = {
  // United States
  ATL: ['Atlanta', US],
  AUS: ['Austin', US],
  BNA: ['Nashville', US],
  BOS: ['Boston', US],
  BWI: ['Baltimore', US],
  CLT: ['Charlotte', US],
  DCA: ['Washington', US],
  DEN: ['Denver', US],
  DFW: ['Dallas', US],
  DTW: ['Detroit', US],
  EWR: ['Newark', US],
  FLL: ['Fort Lauderdale', US],
  HNL: ['Honolulu', US],
  IAD: ['Washington', US],
  IAH: ['Houston', US],
  JFK: ['New York', US],
  LAS: ['Las Vegas', US],
  LAX: ['Los Angeles', US],
  LGA: ['New York', US],
  MCO: ['Orlando', US],
  MDW: ['Chicago', US],
  MIA: ['Miami', US],
  MSP: ['Minneapolis', US],
  MSY: ['New Orleans', US],
  OAK: ['Oakland', US],
  ORD: ['Chicago', US],
  PDX: ['Portland', US],
  PHL: ['Philadelphia', US],
  PHX: ['Phoenix', US],
  SAN: ['San Diego', US],
  SEA: ['Seattle', US],
  SFO: ['San Francisco', US],
  SJC: ['San Jose', US],
  SLC: ['Salt Lake City', US],
  STL: ['St. Louis', US],
  TPA: ['Tampa', US],
  // Canada and Mexico
  YUL: ['Montreal', 'Canada'],
  YVR: ['Vancouver', 'Canada'],
  YYC: ['Calgary', 'Canada'],
  YYZ: ['Toronto', 'Canada'],
  CUN: ['Cancún', 'Mexico'],
  MEX: ['Mexico City', 'Mexico'],
  // Europe
  AMS: ['Amsterdam', 'Netherlands'],
  ARN: ['Stockholm', 'Sweden'],
  ATH: ['Athens', 'Greece'],
  BCN: ['Barcelona', 'Spain'],
  BER: ['Berlin', 'Germany'],
  BRU: ['Brussels', 'Belgium'],
  CDG: ['Paris', 'France'],
  CPH: ['Copenhagen', 'Denmark'],
  DUB: ['Dublin', 'Ireland'],
  EDI: ['Edinburgh', 'United Kingdom'],
  FCO: ['Rome', 'Italy'],
  FRA: ['Frankfurt', 'Germany'],
  GVA: ['Geneva', 'Switzerland'],
  HEL: ['Helsinki', 'Finland'],
  IST: ['Istanbul', 'Turkey'],
  KEF: ['Reykjavík', 'Iceland'],
  LGW: ['London', 'United Kingdom'],
  LHR: ['London', 'United Kingdom'],
  LIS: ['Lisbon', 'Portugal'],
  MAD: ['Madrid', 'Spain'],
  MAN: ['Manchester', 'United Kingdom'],
  MUC: ['Munich', 'Germany'],
  MXP: ['Milan', 'Italy'],
  NCE: ['Nice', 'France'],
  ORY: ['Paris', 'France'],
  OPO: ['Porto', 'Portugal'],
  OSL: ['Oslo', 'Norway'],
  PRG: ['Prague', 'Czechia'],
  VIE: ['Vienna', 'Austria'],
  WAW: ['Warsaw', 'Poland'],
  ZRH: ['Zurich', 'Switzerland'],
  // Middle East, Africa, Asia, Oceania, South America
  AKL: ['Auckland', 'New Zealand'],
  BKK: ['Bangkok', 'Thailand'],
  BOG: ['Bogotá', 'Colombia'],
  CPT: ['Cape Town', 'South Africa'],
  DEL: ['Delhi', 'India'],
  DOH: ['Doha', 'Qatar'],
  DPS: ['Denpasar', 'Indonesia'],
  DXB: ['Dubai', 'United Arab Emirates'],
  EZE: ['Buenos Aires', 'Argentina'],
  GRU: ['São Paulo', 'Brazil'],
  HKG: ['Hong Kong', 'Hong Kong'],
  HND: ['Tokyo', 'Japan'],
  ICN: ['Seoul', 'South Korea'],
  JNB: ['Johannesburg', 'South Africa'],
  KIX: ['Osaka', 'Japan'],
  LIM: ['Lima', 'Peru'],
  MEL: ['Melbourne', 'Australia'],
  NRT: ['Tokyo', 'Japan'],
  SIN: ['Singapore', 'Singapore'],
  SYD: ['Sydney', 'Australia'],
};

export function airportPlace(code: string): { city: string; country: string } | null {
  const found = AIRPORTS[code.trim().toUpperCase()];
  return found ? { city: found[0], country: found[1] } : null;
}
