// Generated by scripts/supabase-apply.mjs --types. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.18';
  };
  public: {
    Tables: {
      bookings: {
        Row: {
          created_at: string;
          data: Json;
          id: string;
          original_path: string | null;
          trip_id: string;
          type: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          data?: Json;
          id?: string;
          original_path?: string | null;
          trip_id: string;
          type: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          created_at?: string;
          data?: Json;
          id?: string;
          original_path?: string | null;
          trip_id?: string;
          type?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'bookings_trip_id_user_id_fkey';
            columns: ['trip_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id', 'user_id'];
          },
        ];
      };
      bucket_items: {
        Row: {
          created_at: string;
          duration_minutes: number | null;
          fixed_date: string | null;
          fixed_time: string | null;
          id: string;
          place_id: string | null;
          source: string | null;
          trip_id: string;
          updated_at: string;
          user_id: string;
          window_end: string | null;
          window_start: string | null;
        };
        Insert: {
          created_at?: string;
          duration_minutes?: number | null;
          fixed_date?: string | null;
          fixed_time?: string | null;
          id?: string;
          place_id?: string | null;
          source?: string | null;
          trip_id: string;
          updated_at?: string;
          user_id?: string;
          window_end?: string | null;
          window_start?: string | null;
        };
        Update: {
          created_at?: string;
          duration_minutes?: number | null;
          fixed_date?: string | null;
          fixed_time?: string | null;
          id?: string;
          place_id?: string | null;
          source?: string | null;
          trip_id?: string;
          updated_at?: string;
          user_id?: string;
          window_end?: string | null;
          window_start?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'bucket_items_place_id_user_id_fkey';
            columns: ['place_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'places';
            referencedColumns: ['id', 'user_id'];
          },
          {
            foreignKeyName: 'bucket_items_trip_id_user_id_fkey';
            columns: ['trip_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id', 'user_id'];
          },
        ];
      };
      documents: {
        Row: {
          country: string | null;
          created_at: string;
          expires_on: string | null;
          id: string;
          image_path: string | null;
          image_paths: string[];
          number: string | null;
          type: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          country?: string | null;
          created_at?: string;
          expires_on?: string | null;
          id?: string;
          image_path?: string | null;
          image_paths?: string[];
          number?: string | null;
          type: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          country?: string | null;
          created_at?: string;
          expires_on?: string | null;
          id?: string;
          image_path?: string | null;
          image_paths?: string[];
          number?: string | null;
          type?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      expenses: {
        Row: {
          amount_minor: number;
          booking_id: string | null;
          category: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          id: string;
          paid_at: string | null;
          trip_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          amount_minor: number;
          booking_id?: string | null;
          category?: string | null;
          created_at?: string;
          currency: string;
          description?: string | null;
          id?: string;
          paid_at?: string | null;
          trip_id: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          amount_minor?: number;
          booking_id?: string | null;
          category?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          id?: string;
          paid_at?: string | null;
          trip_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'expenses_booking_fkey';
            columns: ['booking_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'bookings';
            referencedColumns: ['id', 'user_id'];
          },
          {
            foreignKeyName: 'expenses_trip_id_user_id_fkey';
            columns: ['trip_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id', 'user_id'];
          },
        ];
      };
      itinerary_items: {
        Row: {
          booking_id: string | null;
          created_at: string;
          day: string;
          duration_minutes: number | null;
          fixed: boolean;
          id: string;
          kind: string;
          notes: string | null;
          place_id: string | null;
          start_time: string | null;
          title: string | null;
          trip_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          booking_id?: string | null;
          created_at?: string;
          day: string;
          duration_minutes?: number | null;
          fixed?: boolean;
          id?: string;
          kind: string;
          notes?: string | null;
          place_id?: string | null;
          start_time?: string | null;
          title?: string | null;
          trip_id: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          booking_id?: string | null;
          created_at?: string;
          day?: string;
          duration_minutes?: number | null;
          fixed?: boolean;
          id?: string;
          kind?: string;
          notes?: string | null;
          place_id?: string | null;
          start_time?: string | null;
          title?: string | null;
          trip_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'itinerary_items_booking_id_user_id_fkey';
            columns: ['booking_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'bookings';
            referencedColumns: ['id', 'user_id'];
          },
          {
            foreignKeyName: 'itinerary_items_place_id_user_id_fkey';
            columns: ['place_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'places';
            referencedColumns: ['id', 'user_id'];
          },
          {
            foreignKeyName: 'itinerary_items_trip_id_user_id_fkey';
            columns: ['trip_id', 'user_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id', 'user_id'];
          },
        ];
      };
      places: {
        Row: {
          address: string | null;
          created_at: string;
          id: string;
          kind: string | null;
          lat: number | null;
          lng: number | null;
          name: string;
          photo_url: string | null;
          source_url: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          address?: string | null;
          created_at?: string;
          id?: string;
          kind?: string | null;
          lat?: number | null;
          lng?: number | null;
          name: string;
          photo_url?: string | null;
          source_url?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          address?: string | null;
          created_at?: string;
          id?: string;
          kind?: string | null;
          lat?: number | null;
          lng?: number | null;
          name?: string;
          photo_url?: string | null;
          source_url?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      saved_links: {
        Row: {
          created_at: string;
          id: string;
          place_ids: string[];
          platform: string | null;
          thumbnail_url: string | null;
          title: string | null;
          updated_at: string;
          url: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          place_ids?: string[];
          platform?: string | null;
          thumbnail_url?: string | null;
          title?: string | null;
          updated_at?: string;
          url: string;
          user_id?: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          place_ids?: string[];
          platform?: string | null;
          thumbnail_url?: string | null;
          title?: string | null;
          updated_at?: string;
          url?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      trips: {
        Row: {
          budget_currency: string | null;
          budget_minor: number | null;
          city: string;
          country: string | null;
          cover_photo_credit: Json | null;
          cover_photo_url: string | null;
          created_at: string;
          end_date: string;
          id: string;
          lat: number | null;
          lng: number | null;
          start_date: string;
          timezone: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          budget_currency?: string | null;
          budget_minor?: number | null;
          city: string;
          country?: string | null;
          cover_photo_credit?: Json | null;
          cover_photo_url?: string | null;
          created_at?: string;
          end_date: string;
          id?: string;
          lat?: number | null;
          lng?: number | null;
          start_date: string;
          timezone: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          budget_currency?: string | null;
          budget_minor?: number | null;
          city?: string;
          country?: string | null;
          cover_photo_credit?: Json | null;
          cover_photo_url?: string | null;
          created_at?: string;
          end_date?: string;
          id?: string;
          lat?: number | null;
          lng?: number | null;
          start_date?: string;
          timezone?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
