// Generated by scripts/supabase-apply.mjs --types. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: '14.18';
  };
  public: {
    Tables: {
      bookings: {
        Row: {
          created_at: string;
          data: Json;
          id: string;
          original_path: string | null;
          trip_id: string;
          type: string;
          updated_at: string;
          user_id: string;
          visibility: string;
        };
        Insert: {
          created_at?: string;
          data?: Json;
          id?: string;
          original_path?: string | null;
          trip_id: string;
          type: string;
          updated_at?: string;
          user_id?: string;
          visibility?: string;
        };
        Update: {
          created_at?: string;
          data?: Json;
          id?: string;
          original_path?: string | null;
          trip_id?: string;
          type?: string;
          updated_at?: string;
          user_id?: string;
          visibility?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'bookings_trip_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
        ];
      };
      bucket_items: {
        Row: {
          created_at: string;
          duration_minutes: number | null;
          fixed_date: string | null;
          fixed_time: string | null;
          id: string;
          place_id: string | null;
          saved_link_id: string | null;
          source: string | null;
          title: string | null;
          trip_id: string;
          updated_at: string;
          user_id: string;
          window_end: string | null;
          window_start: string | null;
        };
        Insert: {
          created_at?: string;
          duration_minutes?: number | null;
          fixed_date?: string | null;
          fixed_time?: string | null;
          id?: string;
          place_id?: string | null;
          saved_link_id?: string | null;
          source?: string | null;
          title?: string | null;
          trip_id: string;
          updated_at?: string;
          user_id?: string;
          window_end?: string | null;
          window_start?: string | null;
        };
        Update: {
          created_at?: string;
          duration_minutes?: number | null;
          fixed_date?: string | null;
          fixed_time?: string | null;
          id?: string;
          place_id?: string | null;
          saved_link_id?: string | null;
          source?: string | null;
          title?: string | null;
          trip_id?: string;
          updated_at?: string;
          user_id?: string;
          window_end?: string | null;
          window_start?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'bucket_items_place_fkey';
            columns: ['place_id'];
            isOneToOne: false;
            referencedRelation: 'places';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'bucket_items_saved_link_fkey';
            columns: ['saved_link_id'];
            isOneToOne: false;
            referencedRelation: 'saved_links';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'bucket_items_trip_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
        ];
      };
      document_shares: {
        Row: {
          created_at: string;
          document_id: string;
          trip_id: string;
        };
        Insert: {
          created_at?: string;
          document_id: string;
          trip_id: string;
        };
        Update: {
          created_at?: string;
          document_id?: string;
          trip_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'document_shares_document_id_fkey';
            columns: ['document_id'];
            isOneToOne: false;
            referencedRelation: 'documents';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'document_shares_trip_id_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
        ];
      };
      documents: {
        Row: {
          country: string | null;
          created_at: string;
          expires_on: string | null;
          id: string;
          image_path: string | null;
          image_paths: string[];
          number: string | null;
          type: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          country?: string | null;
          created_at?: string;
          expires_on?: string | null;
          id?: string;
          image_path?: string | null;
          image_paths?: string[];
          number?: string | null;
          type: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          country?: string | null;
          created_at?: string;
          expires_on?: string | null;
          id?: string;
          image_path?: string | null;
          image_paths?: string[];
          number?: string | null;
          type?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      expenses: {
        Row: {
          amount_minor: number;
          booking_id: string | null;
          category: string | null;
          created_at: string;
          currency: string;
          description: string | null;
          id: string;
          paid_at: string | null;
          trip_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          amount_minor: number;
          booking_id?: string | null;
          category?: string | null;
          created_at?: string;
          currency: string;
          description?: string | null;
          id?: string;
          paid_at?: string | null;
          trip_id: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          amount_minor?: number;
          booking_id?: string | null;
          category?: string | null;
          created_at?: string;
          currency?: string;
          description?: string | null;
          id?: string;
          paid_at?: string | null;
          trip_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'expenses_booking_fkey';
            columns: ['booking_id'];
            isOneToOne: false;
            referencedRelation: 'bookings';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'expenses_trip_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
        ];
      };
      flight_status_cache: {
        Row: {
          fetched_at: string;
          key: string;
          status: Json | null;
        };
        Insert: {
          fetched_at?: string;
          key: string;
          status?: Json | null;
        };
        Update: {
          fetched_at?: string;
          key?: string;
          status?: Json | null;
        };
        Relationships: [];
      };
      flight_status_usage: {
        Row: {
          month: string;
          units: number;
        };
        Insert: {
          month: string;
          units?: number;
        };
        Update: {
          month?: string;
          units?: number;
        };
        Relationships: [];
      };
      itinerary_items: {
        Row: {
          added_by: string | null;
          booking_id: string | null;
          created_at: string;
          day: string;
          duration_minutes: number | null;
          fixed: boolean;
          id: string;
          kind: string;
          notes: string | null;
          place_id: string | null;
          start_time: string | null;
          title: string | null;
          trip_id: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          added_by?: string | null;
          booking_id?: string | null;
          created_at?: string;
          day: string;
          duration_minutes?: number | null;
          fixed?: boolean;
          id?: string;
          kind: string;
          notes?: string | null;
          place_id?: string | null;
          start_time?: string | null;
          title?: string | null;
          trip_id: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          added_by?: string | null;
          booking_id?: string | null;
          created_at?: string;
          day?: string;
          duration_minutes?: number | null;
          fixed?: boolean;
          id?: string;
          kind?: string;
          notes?: string | null;
          place_id?: string | null;
          start_time?: string | null;
          title?: string | null;
          trip_id?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'itinerary_items_added_by_fkey';
            columns: ['added_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'itinerary_items_booking_fkey';
            columns: ['booking_id'];
            isOneToOne: false;
            referencedRelation: 'bookings';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'itinerary_items_place_fkey';
            columns: ['place_id'];
            isOneToOne: false;
            referencedRelation: 'places';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'itinerary_items_trip_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
        ];
      };
      places: {
        Row: {
          address: string | null;
          created_at: string;
          id: string;
          kind: string | null;
          lat: number | null;
          lng: number | null;
          name: string;
          photo_url: string | null;
          source_url: string | null;
          trip_id: string | null;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          address?: string | null;
          created_at?: string;
          id?: string;
          kind?: string | null;
          lat?: number | null;
          lng?: number | null;
          name: string;
          photo_url?: string | null;
          source_url?: string | null;
          trip_id?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          address?: string | null;
          created_at?: string;
          id?: string;
          kind?: string | null;
          lat?: number | null;
          lng?: number | null;
          name?: string;
          photo_url?: string | null;
          source_url?: string | null;
          trip_id?: string | null;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'places_trip_id_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
        ];
      };
      profiles: {
        Row: {
          cashapp: string | null;
          created_at: string;
          display_name: string;
          id: string;
          updated_at: string;
          venmo: string | null;
          zelle: string | null;
        };
        Insert: {
          cashapp?: string | null;
          created_at?: string;
          display_name: string;
          id: string;
          updated_at?: string;
          venmo?: string | null;
          zelle?: string | null;
        };
        Update: {
          cashapp?: string | null;
          created_at?: string;
          display_name?: string;
          id?: string;
          updated_at?: string;
          venmo?: string | null;
          zelle?: string | null;
        };
        Relationships: [];
      };
      saved_links: {
        Row: {
          author: string | null;
          created_at: string;
          id: string;
          place_ids: string[];
          platform: string | null;
          thumbnail_url: string | null;
          title: string | null;
          trip_id: string | null;
          updated_at: string;
          url: string;
          user_id: string;
        };
        Insert: {
          author?: string | null;
          created_at?: string;
          id?: string;
          place_ids?: string[];
          platform?: string | null;
          thumbnail_url?: string | null;
          title?: string | null;
          trip_id?: string | null;
          updated_at?: string;
          url: string;
          user_id?: string;
        };
        Update: {
          author?: string | null;
          created_at?: string;
          id?: string;
          place_ids?: string[];
          platform?: string | null;
          thumbnail_url?: string | null;
          title?: string | null;
          trip_id?: string | null;
          updated_at?: string;
          url?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'saved_links_trip_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
        ];
      };
      trip_invites: {
        Row: {
          created_at: string;
          created_by: string | null;
          revoked_at: string | null;
          token: string;
          trip_id: string;
        };
        Insert: {
          created_at?: string;
          created_by?: string | null;
          revoked_at?: string | null;
          token: string;
          trip_id: string;
        };
        Update: {
          created_at?: string;
          created_by?: string | null;
          revoked_at?: string | null;
          token?: string;
          trip_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_invites_created_by_fkey';
            columns: ['created_by'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_invites_trip_id_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
        ];
      };
      trip_members: {
        Row: {
          joined_at: string;
          role: string;
          trip_id: string;
          user_id: string;
        };
        Insert: {
          joined_at?: string;
          role?: string;
          trip_id: string;
          user_id: string;
        };
        Update: {
          joined_at?: string;
          role?: string;
          trip_id?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_members_trip_id_fkey';
            columns: ['trip_id'];
            isOneToOne: false;
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_members_user_id_fkey';
            columns: ['user_id'];
            isOneToOne: false;
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      trips: {
        Row: {
          budget_currency: string | null;
          budget_minor: number | null;
          city: string;
          country: string | null;
          cover_photo_credit: Json | null;
          cover_photo_url: string | null;
          created_at: string;
          end_date: string;
          id: string;
          lat: number | null;
          lng: number | null;
          start_date: string;
          timezone: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          budget_currency?: string | null;
          budget_minor?: number | null;
          city: string;
          country?: string | null;
          cover_photo_credit?: Json | null;
          cover_photo_url?: string | null;
          created_at?: string;
          end_date: string;
          id?: string;
          lat?: number | null;
          lng?: number | null;
          start_date: string;
          timezone: string;
          updated_at?: string;
          user_id?: string;
        };
        Update: {
          budget_currency?: string | null;
          budget_minor?: number | null;
          city?: string;
          country?: string | null;
          cover_photo_credit?: Json | null;
          cover_photo_url?: string | null;
          created_at?: string;
          end_date?: string;
          id?: string;
          lat?: number | null;
          lng?: number | null;
          start_date?: string;
          timezone?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      accept_invite: { Args: { invite: string }; Returns: string };
      can_read_original: { Args: { path: string }; Returns: boolean };
      city_links: {
        Args: { p_city: string };
        Returns: {
          place_count: number;
          thumbnail_url: string;
          title: string;
          url: string;
        }[];
      };
      create_invite: { Args: { trip: string }; Returns: string };
      invite_preview: {
        Args: { invite: string };
        Returns: {
          already_member: boolean;
          city: string;
          cover_photo_url: string;
          end_date: string;
          inviter_name: string;
          member_count: number;
          start_date: string;
          trip_id: string;
        }[];
      };
      is_co_member: { Args: { other: string }; Returns: boolean };
      is_document_shared_with_me: {
        Args: { document: string };
        Returns: boolean;
      };
      is_trip_member: { Args: { trip: string }; Returns: boolean };
      is_trip_owner: { Args: { trip: string }; Returns: boolean };
      owns_document: { Args: { document: string }; Returns: boolean };
      reserve_flight_status_units: {
        Args: { p_limit: number; p_month: string; p_units: number };
        Returns: boolean;
      };
      reset_invite: { Args: { trip: string }; Returns: string };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, '__InternalSupabase'>;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, 'public'>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Views'])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema['Tables'] & DefaultSchema['Views'])
    ? (DefaultSchema['Tables'] & DefaultSchema['Views'])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema['Tables'] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables']
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions['schema']]['Tables'][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema['Tables']
    ? DefaultSchema['Tables'][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema['Enums'] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums']
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions['schema']]['Enums'][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema['Enums']
    ? DefaultSchema['Enums'][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    keyof DefaultSchema['CompositeTypes'] | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes']
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions['schema']]['CompositeTypes'][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema['CompositeTypes']
    ? DefaultSchema['CompositeTypes'][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {},
  },
} as const;
