/**
 * The currency a traveller pays in at the destination, from the trip's country as stored (an
 * English country name, e.g. `United States`, or a two-letter code). Covers the countries whose
 * currency Frankfurter (ECB rates) can convert; anything else returns null and the caller falls
 * back to the home currency. Pure TypeScript.
 */

const EURO_COUNTRIES = [
  'Austria',
  'Belgium',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Ireland',
  'Italy',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Netherlands',
  'Portugal',
  'Slovakia',
  'Slovenia',
  'Spain',
  // Euro users outside the EU.
  'Andorra',
  'Monaco',
  'Montenegro',
  'San Marino',
  'Vatican City',
  'Kosovo',
];

/** Country name → ISO 4217 code. */
const BY_NAME: Record<string, string> = {
  ...Object.fromEntries(EURO_COUNTRIES.map((c) => [c, 'EUR'])),
  'United States': 'USD',
  'United States of America': 'USD',
  USA: 'USD',
  'Puerto Rico': 'USD',
  Ecuador: 'USD',
  'El Salvador': 'USD',
  Panama: 'USD',
  Canada: 'CAD',
  Mexico: 'MXN',
  Brazil: 'BRL',
  'United Kingdom': 'GBP',
  UK: 'GBP',
  England: 'GBP',
  Scotland: 'GBP',
  Wales: 'GBP',
  'Northern Ireland': 'GBP',
  Switzerland: 'CHF',
  Liechtenstein: 'CHF',
  Sweden: 'SEK',
  Norway: 'NOK',
  Denmark: 'DKK',
  Iceland: 'ISK',
  Poland: 'PLN',
  Czechia: 'CZK',
  'Czech Republic': 'CZK',
  Hungary: 'HUF',
  Romania: 'RON',
  Turkey: 'TRY',
  Türkiye: 'TRY',
  Israel: 'ILS',
  'South Africa': 'ZAR',
  Japan: 'JPY',
  China: 'CNY',
  'Hong Kong': 'HKD',
  Singapore: 'SGD',
  'South Korea': 'KRW',
  'Republic of Korea': 'KRW',
  Korea: 'KRW',
  India: 'INR',
  Indonesia: 'IDR',
  Malaysia: 'MYR',
  Philippines: 'PHP',
  Thailand: 'THB',
  Australia: 'AUD',
  'New Zealand': 'NZD',
};

/** Two-letter ISO 3166 code → ISO 4217 code, for countries stored as codes. */
const BY_CODE: Record<string, string> = {
  US: 'USD',
  PR: 'USD',
  CA: 'CAD',
  MX: 'MXN',
  BR: 'BRL',
  GB: 'GBP',
  CH: 'CHF',
  LI: 'CHF',
  SE: 'SEK',
  NO: 'NOK',
  DK: 'DKK',
  IS: 'ISK',
  PL: 'PLN',
  CZ: 'CZK',
  HU: 'HUF',
  RO: 'RON',
  TR: 'TRY',
  IL: 'ILS',
  ZA: 'ZAR',
  JP: 'JPY',
  CN: 'CNY',
  HK: 'HKD',
  SG: 'SGD',
  KR: 'KRW',
  IN: 'INR',
  ID: 'IDR',
  MY: 'MYR',
  PH: 'PHP',
  TH: 'THB',
  AU: 'AUD',
  NZ: 'NZD',
  ...Object.fromEntries(
    [
      'AT',
      'BE',
      'BG',
      'HR',
      'CY',
      'EE',
      'FI',
      'FR',
      'DE',
      'GR',
      'IE',
      'IT',
      'LV',
      'LT',
      'LU',
      'MT',
      'NL',
      'PT',
      'SK',
      'SI',
      'ES',
      'AD',
      'MC',
      'ME',
      'SM',
      'VA',
    ].map((c) => [c, 'EUR']),
  ),
};

const NAMES_LOWER = new Map(Object.entries(BY_NAME).map(([k, v]) => [k.toLowerCase(), v]));

/** `Japan` → `JPY`, `FR` → `EUR`, `Narnia` → null. */
export function currencyForCountry(country: string | null | undefined): string | null {
  const value = country?.trim();
  if (!value) return null;
  if (/^[A-Za-z]{2}$/.test(value)) return BY_CODE[value.toUpperCase()] ?? null;
  return NAMES_LOWER.get(value.toLowerCase()) ?? null;
}
