#!/usr/bin/env node
// Applies pending supabase/migrations/*.sql and supabase/auth.json to the project through the
// Management API, recording each migration in internal._migrations. Re-running is a no-op.
//
//   SUPABASE_ACCESS_TOKEN=… node scripts/supabase-apply.mjs           apply migrations + auth config
//   SUPABASE_ACCESS_TOKEN=… node scripts/supabase-apply.mjs --types   also regenerate DB types
//
// Used locally and by CI on main (.github/workflows/ci.yml → Supabase).

import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { api, literal, sql } from './supabase-api.mjs';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const migrationsDir = path.join(root, 'supabase', 'migrations');
const typesFile = path.join(root, 'src', 'services', 'database.types.ts');

async function applyMigrations() {
  await sql(`
    create schema if not exists internal;
    revoke all on schema internal from public, anon, authenticated;
    create table if not exists internal._migrations (
      name text primary key,
      checksum text not null,
      applied_at timestamptz not null default now()
    );
  `);
  const applied = new Map(
    (await sql('select name, checksum from internal._migrations')).map((r) => [r.name, r.checksum]),
  );

  const files = readdirSync(migrationsDir)
    .filter((f) => f.endsWith('.sql'))
    .sort();
  let count = 0;
  for (const name of files) {
    const body = readFileSync(path.join(migrationsDir, name), 'utf8');
    const checksum = createHash('sha256').update(body).digest('hex');
    if (applied.has(name)) {
      if (applied.get(name) !== checksum) {
        throw new Error(
          `${name} was edited after it was applied. Add a new migration instead of changing it.`,
        );
      }
      continue;
    }
    // One transaction per migration: it applies fully and is recorded, or not at all.
    await sql(
      `begin;\n${body}\n;insert into internal._migrations (name, checksum) ` +
        `values (${literal(name)}, ${literal(checksum)});\ncommit;`,
    );
    console.log(`applied ${name}`);
    count += 1;
  }
  console.log(count ? `${count} migration(s) applied` : 'migrations up to date');
}

async function applyAuthConfig() {
  const wanted = JSON.parse(readFileSync(path.join(root, 'supabase', 'auth.json'), 'utf8'));
  const current = await api('GET', '/config/auth');
  const changes = Object.fromEntries(
    Object.entries(wanted).filter(([key, value]) => current[key] !== value),
  );
  if (Object.keys(changes).length === 0) {
    console.log('auth config up to date');
    return;
  }
  await api('PATCH', '/config/auth', changes);
  console.log(`auth config updated: ${Object.keys(changes).join(', ')}`);
}

async function generateTypes() {
  const { types } = await api('GET', '/types/typescript?included_schemas=public');
  writeFileSync(
    typesFile,
    `// Generated by scripts/supabase-apply.mjs --types. Do not edit.\n${types}`,
  );
  execFileSync('npx', ['prettier', '--write', typesFile], { cwd: root, stdio: 'ignore' });
  console.log(`wrote ${path.relative(root, typesFile)}`);
}

try {
  await applyMigrations();
  await applyAuthConfig();
  if (process.argv.includes('--types')) await generateTypes();
} catch (error) {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
}
